### ISSUE TITLE
Inquiries about the release version

### ISSUE THREAD

**Issue by hxx-163mail** [nnstreamer/nnstreamer#4798]
1. The latest release version of the nnstreamer main library is currently v2.4.0, which is two years old. Why hasn't a new version been released yet?

2. I'd like to know when the next official release version is expected to be released.

**Comment by myungjoo** [comment]
We have been shipping to products without version changes. :(

Anyway, we have just released for a new product sets last month; thus, we can mark new version soon.

I will update the version when the pending bugfixes (in the Github pull requests) are merged.

**Comment by myungjoo** [comment]
#4799 coming.

**Comment by hxx-163mail** [comment]
Hello, I see your team may still have some bugs to fix, but I'd still like to ask when nnstreamer version v2.6.0 is expected to be officially released? This month or next month?

thx
